# Generated by Django 4.2.2 on 2023-06-26 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
