# Generated by Django 4.2.2 on 2023-06-26 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0002_remove_post_likes_delete_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="tags",
            new_name="hashtags",
        ),
    ]
